name: PR build
on: pull_request

jobs:
  pr_build:
    name: PR build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - run: pnpm install
      - run: pnpm build
